version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mvc_php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    container_name: mvc_nginx
    depends_on:
      - app


  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mvc_db

