version: "3"

services:
   app:
     build:
       context: .
       dockerfile: docker/app/Dockerfile
     container_name: chambe_php
     volumes:
       - ./:/var/www/html

   nginx:
     image: nginx:latest
     ports:
       - "8080:80"
     volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
     container_name: chambe_nginx
     depends_on:
       - app


   phpmyadmin:
     image: phpmyadmin
     restart: always
     ports:
       - "8070:80"
     environment:
        PMA_HOST: db
        PMA_PORT: 3306

   db:
     image: mysql:8.0
     restart: always
     volumes:
       - ./docker/mysql/data:/var/lib/mysql
     environment:
       MYSQL_DATABASE: chamberonne
       MYSQL_ROOT_PASSWORD: root
     ports:
       - "7776:3306"
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
     container_name: chambe_db

